<h2>Get the distances between each cardiac arrest and the nearest existing AED location<h2>

In [23]:
import numpy as np
import pandas as pd
distances = np.load('/Users/user/Documents/GitHub/modern_data_analytics_2024/transformed_data/intervention_to_aed_distances_km.npy')
distances.shape
min_distances = np.min(distances, axis=1)
min_indices = np.argmin(distances, axis=1)

[0.26002494 0.27408346 0.40308063 ... 5.61144392 0.36937148 0.14699724]
[9988 7013 3178 ... 3045 3888 3846]


In [33]:
min_indices.shape
intervention_coordinates = pd.read_csv("/Users/user/Documents/GitHub/modern_data_analytics_2024/transformed_data/intervention_coordinates.csv")
aed_locations_full = pd.read_csv("/Users/user/Documents/GitHub/modern_data_analytics_2024/transformed_data/aed_locations_full.csv")
aed_public = aed_locations_full.iloc[min_indices, 8]
intervention_id = intervention_coordinates.iloc[:,2]
intervention_aed_mindistance = np.column_stack((intervention_id, min_indices, aed_public, min_distances))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


array([[0, 9988, 'Non-Nee', 0.26002493604498944],
       [1, 7013, 'Y', 0.2740834599135142],
       [2, 3178, nan, 0.4030806315582387],
       ...,
       [32972, 3045, nan, 5.611443924198077],
       [32973, 3888, nan, 0.3693714786927163],
       [32974, 3846, nan, 0.1469972443385638]], dtype=object)